all: hello-1-ee hello-2-ee hello-3-ee

hello-1-ee:hello-1.c
	gcc -o hello-1-ee hello-1.c
hello-2-ee:hello-2.c
	gcc -o hello-2-ee  hello-2.c
hello-3-ee:hello-3.c
	gcc -o hello-3-ee  hello-3.c

clean:
	rm -rf *.o *-ee

